---
title: "EjercicioCualitativos"
author: "Gabriel"
date: '2022-03-23'
output: html_document
---

### Pregunta 1

```{r}
library(MASS)

br = birthwt
str(br)
head(br)
br$race = as.factor(br$race)
str(br)
br = br
```

### Pregunta 2

```{r}
t1 = table(br$race, br$low)
t1
dimnames(t1) = list(
  Raza = c("blanca", "negra", "otra"),
  IndicadorPeso = c("<2.5kg", ">2.5kg")
)
prop.table(t1, margin = 1)
```

### Pregunta 3

```{r}
t1
dimnames(t1) = list(
  Raza = c("blanca", "negra", "otra"),
  IndicadorPeso = c(">2.5kg", "<2.5kg")
)
t1 = t1
mosaicplot(prop.table(t1, margin = 1),
           main = "Grafico mosaico de las variables 'race' y 'low'",
           col = c("lightblue", "lightgreen"))
```

### Pregunta 4

```{r}
barplot(prop.table(t1, margin = 1), beside = TRUE, legend.text = TRUE, col = c("lightblue", "lightgreen", "pink"),
        main = "Grafico de barras de frecuencia relativa en base a la raza de madres
        respecto al peso del bebe",
        ylim = c(0, 1))
```

### Pregunta 5

Parece ser que la raza no afecta al peso, en todas las razas hay una proporcio mayor de bebes con peso superior a 2.5kg

Es de notar que para la raza "negra", hay una ligera mayoria en la proporcion de bebes con peso menor a 2.5kg en comparacion con las otras razas

### Pregunta 6

```{r}
#Madre fumadora vs peso bebe
t_1 = table(br$smoke, br$low)
dimnames(t_1) = list(
  Fuma = c("NO", "SI"),
  IndicadorPeso = c(">2.5kg", "<2.5kg")
)
#Grafico mosaico
mosaicplot(prop.table(t_1, margin = 1),
           main = "Grafico mosaico de las variables 'smoke' y 'low'",
           col = c("lightblue", "lightgreen"))
#Grafico de barras
barplot(prop.table(t_1, margin = 1), beside = TRUE, legend.text = TRUE, col = c("lightblue", "lightgreen"),
        main = "Grafico de barras de frecuencia relativa en base a 
        si las madres fuman respecto al peso del bebe",
        ylim = c(0, 1))

#Hipertension de la madre vs peso bebe
t_2 = table(br$ht, br$low)
dimnames(t_2) = list(
  Hipertensa = c("NO", "SI"),
  IndicadorPeso = c(">2.5kg", "<2.5kg")
)
#Grafico mosaico
mosaicplot(prop.table(t_2, margin = 1),
           main = "Grafico mosaico de las variables 'smoke' y 'low'",
           col = c("lightblue", "lightgreen"))
#Grafico de barras
barplot(prop.table(t_2, margin = 1), beside = TRUE, legend.text = TRUE, col = c("lightblue", "lightgreen"),
        main = "Grafico de barras de frecuencia relativa en base a 
        si las madres fuman respecto al peso del bebe",
        ylim = c(0, 1))
```

### Pregunta 7

```{r}
prop.table(table(br[c('smoke', 'low', 'race')]), margin = c(1, 3))
```

### Pregunta 8

```{r}
br$race = factor(br$race, 
                        levels = c(1, 2, 3), 
                        labels = c("white", "black", "other"))
br$smoke = factor(br$smoke, 
                      levels = c(0, 1), 
                      labels = c("No", "Yes"))
br$low = factor(br$low, 
                    levels = c(0, 1), 
                    labels = c(">2.5", "<2.5"))

plot(prop.table(table(br[c("smoke", "low", "race")]), margin = c(1, 3)),
     main = "Gráfico de mosaico de las variables \"race\", \"smoke\" y \"low\"",
     col = c("lightgreen","lightblue", "pink"))

```






